<script>
	import * as Icon from '$lib';
	const random_hex_color_code = () => {
		let n = (Math.random() * 0xfffff * 1000000).toString(16);
		return '#' + n.slice(0, 6);
	};
</script>

<div class="flex flex-wrap p-4">
	<Icon.Accessibility size="40" color={random_hex_color_code()} />
	<Icon.Activity size="40" color={random_hex_color_code()} />
	<Icon.Airplay size="40" color={random_hex_color_code()} />
	<Icon.AlarmCheck size="40" color={random_hex_color_code()} />
	<Icon.AlarmClock size="40" color={random_hex_color_code()} />
	<Icon.AlarmClockOff size="40" color={random_hex_color_code()} />
	<Icon.AlarmMinus size="40" color={random_hex_color_code()} />
	<Icon.AlarmPlus size="40" color={random_hex_color_code()} />
	<Icon.Album size="40" color={random_hex_color_code()} />
	<Icon.AlertCircle size="40" color={random_hex_color_code()} />
	<Icon.AlertOctagon size="40" color={random_hex_color_code()} />
	<Icon.AlertTriangle size="40" color={random_hex_color_code()} />
	<Icon.AlignCenter size="40" color={random_hex_color_code()} />
	<Icon.AlignCenterHorizontal size="40" color={random_hex_color_code()} />
	<Icon.AlignCenterVertical size="40" color={random_hex_color_code()} />
	<Icon.AlignEndHorizontal size="40" color={random_hex_color_code()} />
	<Icon.AlignEndVertical size="40" color={random_hex_color_code()} />
	<Icon.AlignHorizontalDistributeCenter size="40" color={random_hex_color_code()} />
	<Icon.AlignHorizontalDistributeEnd size="40" color={random_hex_color_code()} />
	<Icon.AlignHorizontalDistributeStart size="40" color={random_hex_color_code()} />
	<Icon.AlignHorizontalJustifyCenter size="40" color={random_hex_color_code()} />
	<Icon.AlignHorizontalJustifyEnd size="40" color={random_hex_color_code()} />
	<Icon.AlignHorizontalJustifyStart size="40" color={random_hex_color_code()} />
	<Icon.AlignHorizontalSpaceAround size="40" color={random_hex_color_code()} />
	<Icon.AlignHorizontalSpaceBetween size="40" color={random_hex_color_code()} />
	<Icon.AlignJustify size="40" color={random_hex_color_code()} />
	<Icon.AlignLeft size="40" color={random_hex_color_code()} />
	<Icon.AlignRight size="40" color={random_hex_color_code()} />
	<Icon.AlignStartHorizontal size="40" color={random_hex_color_code()} />
	<Icon.AlignStartVertical size="40" color={random_hex_color_code()} />
	<Icon.AlignVerticalDistributeCenter size="40" color={random_hex_color_code()} />
	<Icon.AlignVerticalDistributeEnd size="40" color={random_hex_color_code()} />
	<Icon.AlignVerticalDistributeStart size="40" color={random_hex_color_code()} />
	<Icon.AlignVerticalJustifyCenter size="40" color={random_hex_color_code()} />
	<Icon.AlignVerticalJustifyEnd size="40" color={random_hex_color_code()} />
	<Icon.AlignVerticalJustifyStart size="40" color={random_hex_color_code()} />
	<Icon.AlignVerticalSpaceAround size="40" color={random_hex_color_code()} />
	<Icon.AlignVerticalSpaceBetween size="40" color={random_hex_color_code()} />
	<Icon.Anchor size="40" color={random_hex_color_code()} />
	<Icon.Aperture size="40" color={random_hex_color_code()} />
	<Icon.Archive size="40" color={random_hex_color_code()} />
	<Icon.ArrowBigDown size="40" color={random_hex_color_code()} />
	<Icon.ArrowBigLeft size="40" color={random_hex_color_code()} />
	<Icon.ArrowBigRight size="40" color={random_hex_color_code()} />
	<Icon.ArrowBigUp size="40" color={random_hex_color_code()} />
	<Icon.ArrowDown size="40" color={random_hex_color_code()} />
	<Icon.ArrowDownCircle size="40" color={random_hex_color_code()} />
	<Icon.ArrowDownLeft size="40" color={random_hex_color_code()} />
	<Icon.ArrowDownRight size="40" color={random_hex_color_code()} />
	<Icon.ArrowLeft size="40" color={random_hex_color_code()} />
	<Icon.ArrowLeftCircle size="40" color={random_hex_color_code()} />
	<Icon.ArrowLeftRight size="40" color={random_hex_color_code()} />
	<Icon.ArrowRight size="40" color={random_hex_color_code()} />
	<Icon.ArrowRightCircle size="40" color={random_hex_color_code()} />
	<Icon.ArrowUp size="40" color={random_hex_color_code()} />
	<Icon.ArrowUpCircle size="40" color={random_hex_color_code()} />
	<Icon.ArrowUpLeft size="40" color={random_hex_color_code()} />
	<Icon.ArrowUpRight size="40" color={random_hex_color_code()} />
	<Icon.Asterisk size="40" color={random_hex_color_code()} />
	<Icon.AtSign size="40" color={random_hex_color_code()} />
	<Icon.Award size="40" color={random_hex_color_code()} />
	<Icon.Axe size="40" color={random_hex_color_code()} />
	<Icon.Banknote size="40" color={random_hex_color_code()} />
	<Icon.BarChart size="40" color={random_hex_color_code()} />
	<Icon.BarChart2 size="40" color={random_hex_color_code()} />
	<Icon.Baseline size="40" color={random_hex_color_code()} />
	<Icon.Battery size="40" color={random_hex_color_code()} />
	<Icon.BatteryCharging size="40" color={random_hex_color_code()} />
	<Icon.BatteryFull size="40" color={random_hex_color_code()} />
	<Icon.BatteryLow size="40" color={random_hex_color_code()} />
	<Icon.BatteryMedium size="40" color={random_hex_color_code()} />
	<Icon.Beaker size="40" color={random_hex_color_code()} />
	<Icon.Bell size="40" color={random_hex_color_code()} />
	<Icon.BellMinus size="40" color={random_hex_color_code()} />
	<Icon.BellOff size="40" color={random_hex_color_code()} />
	<Icon.BellPlus size="40" color={random_hex_color_code()} />
	<Icon.BellRing size="40" color={random_hex_color_code()} />
	<Icon.Bike size="40" color={random_hex_color_code()} />
	<Icon.Binary size="40" color={random_hex_color_code()} />
	<Icon.Bitcoin size="40" color={random_hex_color_code()} />
	<Icon.Bluetooth size="40" color={random_hex_color_code()} />
	<Icon.BluetoothConnected size="40" color={random_hex_color_code()} />
	<Icon.BluetoothOff size="40" color={random_hex_color_code()} />
	<Icon.BluetoothSearching size="40" color={random_hex_color_code()} />
	<Icon.Bold size="40" color={random_hex_color_code()} />
	<Icon.Book size="40" color={random_hex_color_code()} />
	<Icon.BookOpen size="40" color={random_hex_color_code()} />
	<Icon.Bookmark size="40" color={random_hex_color_code()} />
	<Icon.BookmarkMinus size="40" color={random_hex_color_code()} />
	<Icon.BookmarkPlus size="40" color={random_hex_color_code()} />
	<Icon.Bot size="40" color={random_hex_color_code()} />
	<Icon.Box size="40" color={random_hex_color_code()} />
	<Icon.BoxSelect size="40" color={random_hex_color_code()} />
	<Icon.Briefcase size="40" color={random_hex_color_code()} />
	<Icon.Brush size="40" color={random_hex_color_code()} />
	<Icon.Bug size="40" color={random_hex_color_code()} />
	<Icon.Building size="40" color={random_hex_color_code()} />
	<Icon.Building2 size="40" color={random_hex_color_code()} />
	<Icon.Bus size="40" color={random_hex_color_code()} />
	<Icon.Calculator size="40" color={random_hex_color_code()} />
	<Icon.Calendar size="40" color={random_hex_color_code()} />
	<Icon.Camera size="40" color={random_hex_color_code()} />
	<Icon.CameraOff size="40" color={random_hex_color_code()} />
	<Icon.Car size="40" color={random_hex_color_code()} />
	<Icon.Carrot size="40" color={random_hex_color_code()} />
	<Icon.Cast size="40" color={random_hex_color_code()} />
	<Icon.Check size="40" color={random_hex_color_code()} />
	<Icon.CheckCircle size="40" color={random_hex_color_code()} />
	<Icon.CheckCircle2 size="40" color={random_hex_color_code()} />
	<Icon.CheckSquare size="40" color={random_hex_color_code()} />
	<Icon.ChevronDown size="40" color={random_hex_color_code()} />
	<Icon.ChevronFirst size="40" color={random_hex_color_code()} />
	<Icon.ChevronLast size="40" color={random_hex_color_code()} />
	<Icon.ChevronLeft size="40" color={random_hex_color_code()} />
	<Icon.ChevronRight size="40" color={random_hex_color_code()} />
	<Icon.ChevronUp size="40" color={random_hex_color_code()} />
	<Icon.ChevronsDown size="40" color={random_hex_color_code()} />
	<Icon.ChevronsDownUp size="40" color={random_hex_color_code()} />
	<Icon.ChevronsLeft size="40" color={random_hex_color_code()} />
	<Icon.ChevronsLeftRight size="40" color={random_hex_color_code()} />
	<Icon.ChevronsRight size="40" color={random_hex_color_code()} />
	<Icon.ChevronsRightLeft size="40" color={random_hex_color_code()} />
	<Icon.ChevronsUp size="40" color={random_hex_color_code()} />
	<Icon.ChevronsUpDown size="40" color={random_hex_color_code()} />
	<Icon.Chrome size="40" color={random_hex_color_code()} />
	<Icon.Circle size="40" color={random_hex_color_code()} />
	<Icon.CircleSlashed size="40" color={random_hex_color_code()} />
	<Icon.Clipboard size="40" color={random_hex_color_code()} />
	<Icon.ClipboardCheck size="40" color={random_hex_color_code()} />
	<Icon.ClipboardCopy size="40" color={random_hex_color_code()} />
	<Icon.ClipboardList size="40" color={random_hex_color_code()} />
	<Icon.ClipboardX size="40" color={random_hex_color_code()} />
	<Icon.Clock size="40" color={random_hex_color_code()} />
	<Icon.Clock1 size="40" color={random_hex_color_code()} />
	<Icon.Clock10 size="40" color={random_hex_color_code()} />
	<Icon.Clock11 size="40" color={random_hex_color_code()} />
	<Icon.Clock12 size="40" color={random_hex_color_code()} />
	<Icon.Clock2 size="40" color={random_hex_color_code()} />
	<Icon.Clock3 size="40" color={random_hex_color_code()} />
	<Icon.Clock4 size="40" color={random_hex_color_code()} />
	<Icon.Clock5 size="40" color={random_hex_color_code()} />
	<Icon.Clock6 size="40" color={random_hex_color_code()} />
	<Icon.Clock7 size="40" color={random_hex_color_code()} />
	<Icon.Clock8 size="40" color={random_hex_color_code()} />
	<Icon.Clock9 size="40" color={random_hex_color_code()} />
	<Icon.Cloud size="40" color={random_hex_color_code()} />
	<Icon.CloudDrizzle size="40" color={random_hex_color_code()} />
	<Icon.CloudFog size="40" color={random_hex_color_code()} />
	<Icon.CloudHail size="40" color={random_hex_color_code()} />
	<Icon.CloudLightning size="40" color={random_hex_color_code()} />
	<Icon.CloudMoon size="40" color={random_hex_color_code()} />
	<Icon.CloudOff size="40" color={random_hex_color_code()} />
	<Icon.CloudRain size="40" color={random_hex_color_code()} />
	<Icon.CloudRainWind size="40" color={random_hex_color_code()} />
	<Icon.CloudSnow size="40" color={random_hex_color_code()} />
	<Icon.CloudSun size="40" color={random_hex_color_code()} />
	<Icon.Cloudy size="40" color={random_hex_color_code()} />
	<Icon.Clover size="40" color={random_hex_color_code()} />
	<Icon.Code size="40" color={random_hex_color_code()} />
	<Icon.Code2 size="40" color={random_hex_color_code()} />
	<Icon.Codepen size="40" color={random_hex_color_code()} />
	<Icon.Codesandbox size="40" color={random_hex_color_code()} />
	<Icon.Coffee size="40" color={random_hex_color_code()} />
	<Icon.Coins size="40" color={random_hex_color_code()} />
	<Icon.Columns size="40" color={random_hex_color_code()} />
	<Icon.Command size="40" color={random_hex_color_code()} />
	<Icon.Compass size="40" color={random_hex_color_code()} />
	<Icon.Contact size="40" color={random_hex_color_code()} />
	<Icon.Contrast size="40" color={random_hex_color_code()} />
	<Icon.Cookie size="40" color={random_hex_color_code()} />
	<Icon.Copy size="40" color={random_hex_color_code()} />
	<Icon.Copyleft size="40" color={random_hex_color_code()} />
	<Icon.Copyright size="40" color={random_hex_color_code()} />
	<Icon.CornerDownLeft size="40" color={random_hex_color_code()} />
	<Icon.CornerDownRight size="40" color={random_hex_color_code()} />
	<Icon.CornerLeftDown size="40" color={random_hex_color_code()} />
	<Icon.CornerLeftUp size="40" color={random_hex_color_code()} />
	<Icon.CornerRightDown size="40" color={random_hex_color_code()} />
	<Icon.CornerRightUp size="40" color={random_hex_color_code()} />
	<Icon.CornerUpLeft size="40" color={random_hex_color_code()} />
	<Icon.CornerUpRight size="40" color={random_hex_color_code()} />
	<Icon.Cpu size="40" color={random_hex_color_code()} />
	<Icon.CreditCard size="40" color={random_hex_color_code()} />
	<Icon.Crop size="40" color={random_hex_color_code()} />
	<Icon.Cross size="40" color={random_hex_color_code()} />
	<Icon.Crosshair size="40" color={random_hex_color_code()} />
	<Icon.Crown size="40" color={random_hex_color_code()} />
	<Icon.Currency size="40" color={random_hex_color_code()} />
	<Icon.Database size="40" color={random_hex_color_code()} />
	<Icon.Delete size="40" color={random_hex_color_code()} />
	<Icon.Dice1 size="40" color={random_hex_color_code()} />
	<Icon.Dice2 size="40" color={random_hex_color_code()} />
	<Icon.Dice3 size="40" color={random_hex_color_code()} />
	<Icon.Dice4 size="40" color={random_hex_color_code()} />
	<Icon.Dice5 size="40" color={random_hex_color_code()} />
	<Icon.Dice6 size="40" color={random_hex_color_code()} />
	<Icon.Disc size="40" color={random_hex_color_code()} />
	<Icon.Divide size="40" color={random_hex_color_code()} />
	<Icon.DivideCircle size="40" color={random_hex_color_code()} />
	<Icon.DivideSquare size="40" color={random_hex_color_code()} />
	<Icon.DollarSign size="40" color={random_hex_color_code()} />
	<Icon.Download size="40" color={random_hex_color_code()} />
	<Icon.DownloadCloud size="40" color={random_hex_color_code()} />
	<Icon.Dribbble size="40" color={random_hex_color_code()} />
	<Icon.Droplet size="40" color={random_hex_color_code()} />
	<Icon.Droplets size="40" color={random_hex_color_code()} />
	<Icon.Drumstick size="40" color={random_hex_color_code()} />
	<Icon.Edit size="40" color={random_hex_color_code()} />
	<Icon.Edit2 size="40" color={random_hex_color_code()} />
	<Icon.Edit3 size="40" color={random_hex_color_code()} />
	<Icon.Egg size="40" color={random_hex_color_code()} />
	<Icon.Equal size="40" color={random_hex_color_code()} />
	<Icon.EqualNot size="40" color={random_hex_color_code()} />
	<Icon.Eraser size="40" color={random_hex_color_code()} />
	<Icon.Euro size="40" color={random_hex_color_code()} />
	<Icon.Expand size="40" color={random_hex_color_code()} />
	<Icon.ExternalLink size="40" color={random_hex_color_code()} />
	<Icon.Eye size="40" color={random_hex_color_code()} />
	<Icon.EyeOff size="40" color={random_hex_color_code()} />
	<Icon.Facebook size="40" color={random_hex_color_code()} />
	<Icon.FastForward size="40" color={random_hex_color_code()} />
	<Icon.Feather size="40" color={random_hex_color_code()} />
	<Icon.Figma size="40" color={random_hex_color_code()} />
	<Icon.File size="40" color={random_hex_color_code()} />
	<Icon.FileCheck size="40" color={random_hex_color_code()} />
	<Icon.FileCheck2 size="40" color={random_hex_color_code()} />
	<Icon.FileCode size="40" color={random_hex_color_code()} />
	<Icon.FileDigit size="40" color={random_hex_color_code()} />
	<Icon.FileInput size="40" color={random_hex_color_code()} />
	<Icon.FileMinus size="40" color={random_hex_color_code()} />
	<Icon.FileMinus2 size="40" color={random_hex_color_code()} />
	<Icon.FileOutput size="40" color={random_hex_color_code()} />
	<Icon.FilePlus size="40" color={random_hex_color_code()} />
	<Icon.FilePlus2 size="40" color={random_hex_color_code()} />
	<Icon.FileSearch size="40" color={random_hex_color_code()} />
	<Icon.FileText size="40" color={random_hex_color_code()} />
	<Icon.FileX size="40" color={random_hex_color_code()} />
	<Icon.FileX2 size="40" color={random_hex_color_code()} />
	<Icon.Files size="40" color={random_hex_color_code()} />
	<Icon.Film size="40" color={random_hex_color_code()} />
	<Icon.Filter size="40" color={random_hex_color_code()} />
	<Icon.Flag size="40" color={random_hex_color_code()} />
	<Icon.FlagOff size="40" color={random_hex_color_code()} />
	<Icon.FlagTriangleLeft size="40" color={random_hex_color_code()} />
	<Icon.FlagTriangleRight size="40" color={random_hex_color_code()} />
	<Icon.Flame size="40" color={random_hex_color_code()} />
	<Icon.Flashlight size="40" color={random_hex_color_code()} />
	<Icon.FlashlightOff size="40" color={random_hex_color_code()} />
	<Icon.FlaskConical size="40" color={random_hex_color_code()} />
	<Icon.FlaskRound size="40" color={random_hex_color_code()} />
	<Icon.Folder size="40" color={random_hex_color_code()} />
	<Icon.FolderMinus size="40" color={random_hex_color_code()} />
	<Icon.FolderOpen size="40" color={random_hex_color_code()} />
	<Icon.FolderPlus size="40" color={random_hex_color_code()} />
	<Icon.FormInput size="40" color={random_hex_color_code()} />
	<Icon.Forward size="40" color={random_hex_color_code()} />
	<Icon.Frame size="40" color={random_hex_color_code()} />
	<Icon.Framer size="40" color={random_hex_color_code()} />
	<Icon.Frown size="40" color={random_hex_color_code()} />
	<Icon.FunctionSquare size="40" color={random_hex_color_code()} />
	<Icon.Gamepad size="40" color={random_hex_color_code()} />
	<Icon.Gamepad2 size="40" color={random_hex_color_code()} />
	<Icon.Gauge size="40" color={random_hex_color_code()} />
	<Icon.Gavel size="40" color={random_hex_color_code()} />
	<Icon.Gem size="40" color={random_hex_color_code()} />
	<Icon.Ghost size="40" color={random_hex_color_code()} />
	<Icon.Gift size="40" color={random_hex_color_code()} />
	<Icon.GitBranch size="40" color={random_hex_color_code()} />
	<Icon.GitBranchPlus size="40" color={random_hex_color_code()} />
	<Icon.GitCommit size="40" color={random_hex_color_code()} />
	<Icon.GitFork size="40" color={random_hex_color_code()} />
	<Icon.GitMerge size="40" color={random_hex_color_code()} />
	<Icon.GitPullRequest size="40" color={random_hex_color_code()} />
	<Icon.Github size="40" color={random_hex_color_code()} />
	<Icon.Gitlab size="40" color={random_hex_color_code()} />
	<Icon.Glasses size="40" color={random_hex_color_code()} />
	<Icon.Globe size="40" color={random_hex_color_code()} />
	<Icon.Globe2 size="40" color={random_hex_color_code()} />
	<Icon.Grab size="40" color={random_hex_color_code()} />
	<Icon.GraduationCap size="40" color={random_hex_color_code()} />
	<Icon.Grid size="40" color={random_hex_color_code()} />
	<Icon.GripHorizontal size="40" color={random_hex_color_code()} />
	<Icon.GripVertical size="40" color={random_hex_color_code()} />
	<Icon.Hammer size="40" color={random_hex_color_code()} />
	<Icon.Hand size="40" color={random_hex_color_code()} />
	<Icon.HandMetal size="40" color={random_hex_color_code()} />
	<Icon.HardDrive size="40" color={random_hex_color_code()} />
	<Icon.HardHat size="40" color={random_hex_color_code()} />
	<Icon.Hash size="40" color={random_hex_color_code()} />
	<Icon.Haze size="40" color={random_hex_color_code()} />
	<Icon.Headphones size="40" color={random_hex_color_code()} />
	<Icon.Heart size="40" color={random_hex_color_code()} />
	<Icon.HeartOff size="40" color={random_hex_color_code()} />
	<Icon.HelpCircle size="40" color={random_hex_color_code()} />
	<Icon.Hexagon size="40" color={random_hex_color_code()} />
	<Icon.Highlighter size="40" color={random_hex_color_code()} />
	<Icon.History size="40" color={random_hex_color_code()} />
	<Icon.Home size="40" color={random_hex_color_code()} />
	<Icon.Hourglass size="40" color={random_hex_color_code()} />
	<Icon.Image size="40" color={random_hex_color_code()} />
	<Icon.ImageMinus size="40" color={random_hex_color_code()} />
	<Icon.ImageOff size="40" color={random_hex_color_code()} />
	<Icon.ImagePlus size="40" color={random_hex_color_code()} />
	<Icon.Import size="40" color={random_hex_color_code()} />
	<Icon.Inbox size="40" color={random_hex_color_code()} />
	<Icon.Indent size="40" color={random_hex_color_code()} />
	<Icon.IndianRupee size="40" color={random_hex_color_code()} />
	<Icon.Infinity size="40" color={random_hex_color_code()} />
	<Icon.Info size="40" color={random_hex_color_code()} />
	<Icon.Inspect size="40" color={random_hex_color_code()} />
	<Icon.Instagram size="40" color={random_hex_color_code()} />
	<Icon.Italic size="40" color={random_hex_color_code()} />
	<Icon.JapaneseYen size="40" color={random_hex_color_code()} />
	<Icon.Key size="40" color={random_hex_color_code()} />
	<Icon.Keyboard size="40" color={random_hex_color_code()} />
	<Icon.Landmark size="40" color={random_hex_color_code()} />
	<Icon.Languages size="40" color={random_hex_color_code()} />
	<Icon.Laptop size="40" color={random_hex_color_code()} />
	<Icon.Laptop2 size="40" color={random_hex_color_code()} />
	<Icon.Lasso size="40" color={random_hex_color_code()} />
	<Icon.LassoSelect size="40" color={random_hex_color_code()} />
	<Icon.Layers size="40" color={random_hex_color_code()} />
	<Icon.Layout size="40" color={random_hex_color_code()} />
	<Icon.LayoutDashboard size="40" color={random_hex_color_code()} />
	<Icon.LayoutGrid size="40" color={random_hex_color_code()} />
	<Icon.LayoutList size="40" color={random_hex_color_code()} />
	<Icon.LayoutTemplate size="40" color={random_hex_color_code()} />
	<Icon.Library size="40" color={random_hex_color_code()} />
	<Icon.LifeBuoy size="40" color={random_hex_color_code()} />
	<Icon.Lightbulb size="40" color={random_hex_color_code()} />
	<Icon.LightbulbOff size="40" color={random_hex_color_code()} />
	<Icon.Link size="40" color={random_hex_color_code()} />
	<Icon.Link2 size="40" color={random_hex_color_code()} />
	<Icon.Link2Off size="40" color={random_hex_color_code()} />
	<Icon.Linkedin size="40" color={random_hex_color_code()} />
	<Icon.List size="40" color={random_hex_color_code()} />
	<Icon.ListChecks size="40" color={random_hex_color_code()} />
	<Icon.ListMinus size="40" color={random_hex_color_code()} />
	<Icon.ListOrdered size="40" color={random_hex_color_code()} />
	<Icon.ListPlus size="40" color={random_hex_color_code()} />
	<Icon.ListX size="40" color={random_hex_color_code()} />
	<Icon.Loader size="40" color={random_hex_color_code()} />
	<Icon.Loader2 size="40" color={random_hex_color_code()} />
	<Icon.Locate size="40" color={random_hex_color_code()} />
	<Icon.LocateFixed size="40" color={random_hex_color_code()} />
	<Icon.LocateOff size="40" color={random_hex_color_code()} />
	<Icon.Lock size="40" color={random_hex_color_code()} />
	<Icon.LogIn size="40" color={random_hex_color_code()} />
	<Icon.LogOut size="40" color={random_hex_color_code()} />
	<Icon.Mail size="40" color={random_hex_color_code()} />
	<Icon.Map size="40" color={random_hex_color_code()} />
	<Icon.MapPin size="40" color={random_hex_color_code()} />
	<Icon.Maximize size="40" color={random_hex_color_code()} />
	<Icon.Maximize2 size="40" color={random_hex_color_code()} />
	<Icon.Megaphone size="40" color={random_hex_color_code()} />
	<Icon.Meh size="40" color={random_hex_color_code()} />
	<Icon.Menu size="40" color={random_hex_color_code()} />
	<Icon.MessageCircle size="40" color={random_hex_color_code()} />
	<Icon.MessageSquare size="40" color={random_hex_color_code()} />
	<Icon.Mic size="40" color={random_hex_color_code()} />
	<Icon.MicOff size="40" color={random_hex_color_code()} />
	<Icon.Milestone size="40" color={random_hex_color_code()} />
	<Icon.Minimize size="40" color={random_hex_color_code()} />
	<Icon.Minimize2 size="40" color={random_hex_color_code()} />
	<Icon.Minus size="40" color={random_hex_color_code()} />
	<Icon.MinusCircle size="40" color={random_hex_color_code()} />
	<Icon.MinusSquare size="40" color={random_hex_color_code()} />
	<Icon.Monitor size="40" color={random_hex_color_code()} />
	<Icon.MonitorOff size="40" color={random_hex_color_code()} />
	<Icon.MonitorSpeaker size="40" color={random_hex_color_code()} />
	<Icon.Moon size="40" color={random_hex_color_code()} />
	<Icon.MoreHorizontal size="40" color={random_hex_color_code()} />
	<Icon.MoreVertical size="40" color={random_hex_color_code()} />
	<Icon.Mountain size="40" color={random_hex_color_code()} />
	<Icon.MountainSnow size="40" color={random_hex_color_code()} />
	<Icon.Mouse size="40" color={random_hex_color_code()} />
	<Icon.MousePointer size="40" color={random_hex_color_code()} />
	<Icon.MousePointer2 size="40" color={random_hex_color_code()} />
	<Icon.MousePointerClick size="40" color={random_hex_color_code()} />
	<Icon.Move size="40" color={random_hex_color_code()} />
	<Icon.MoveDiagonal size="40" color={random_hex_color_code()} />
	<Icon.MoveDiagonal2 size="40" color={random_hex_color_code()} />
	<Icon.MoveHorizontal size="40" color={random_hex_color_code()} />
	<Icon.MoveVertical size="40" color={random_hex_color_code()} />
	<Icon.Music size="40" color={random_hex_color_code()} />
	<Icon.Navigation size="40" color={random_hex_color_code()} />
	<Icon.Navigation2 size="40" color={random_hex_color_code()} />
	<Icon.Network size="40" color={random_hex_color_code()} />
	<Icon.Octagon size="40" color={random_hex_color_code()} />
	<Icon.Option size="40" color={random_hex_color_code()} />
	<Icon.Outdent size="40" color={random_hex_color_code()} />
	<Icon.Package size="40" color={random_hex_color_code()} />
	<Icon.PackageCheck size="40" color={random_hex_color_code()} />
	<Icon.PackageMinus size="40" color={random_hex_color_code()} />
	<Icon.PackagePlus size="40" color={random_hex_color_code()} />
	<Icon.PackageSearch size="40" color={random_hex_color_code()} />
	<Icon.PackageX size="40" color={random_hex_color_code()} />
	<Icon.Palette size="40" color={random_hex_color_code()} />
	<Icon.Palmtree size="40" color={random_hex_color_code()} />
	<Icon.Paperclip size="40" color={random_hex_color_code()} />
	<Icon.Pause size="40" color={random_hex_color_code()} />
	<Icon.PauseCircle size="40" color={random_hex_color_code()} />
	<Icon.PauseOctagon size="40" color={random_hex_color_code()} />
	<Icon.PenTool size="40" color={random_hex_color_code()} />
	<Icon.Pencil size="40" color={random_hex_color_code()} />
	<Icon.Percent size="40" color={random_hex_color_code()} />
	<Icon.PersonStanding size="40" color={random_hex_color_code()} />
	<Icon.Phone size="40" color={random_hex_color_code()} />
	<Icon.PhoneCall size="40" color={random_hex_color_code()} />
	<Icon.PhoneForwarded size="40" color={random_hex_color_code()} />
	<Icon.PhoneIncoming size="40" color={random_hex_color_code()} />
	<Icon.PhoneMissed size="40" color={random_hex_color_code()} />
	<Icon.PhoneOff size="40" color={random_hex_color_code()} />
	<Icon.PhoneOutgoing size="40" color={random_hex_color_code()} />
	<Icon.PieChart size="40" color={random_hex_color_code()} />
	<Icon.PiggyBank size="40" color={random_hex_color_code()} />
	<Icon.Pin size="40" color={random_hex_color_code()} />
	<Icon.Pipette size="40" color={random_hex_color_code()} />
	<Icon.Plane size="40" color={random_hex_color_code()} />
	<Icon.Play size="40" color={random_hex_color_code()} />
	<Icon.PlayCircle size="40" color={random_hex_color_code()} />
	<Icon.PlugZap size="40" color={random_hex_color_code()} />
	<Icon.Plus size="40" color={random_hex_color_code()} />
	<Icon.PlusCircle size="40" color={random_hex_color_code()} />
	<Icon.PlusSquare size="40" color={random_hex_color_code()} />
	<Icon.Pocket size="40" color={random_hex_color_code()} />
	<Icon.Podcast size="40" color={random_hex_color_code()} />
	<Icon.Pointer size="40" color={random_hex_color_code()} />
	<Icon.PoundSterling size="40" color={random_hex_color_code()} />
	<Icon.Power size="40" color={random_hex_color_code()} />
	<Icon.PowerOff size="40" color={random_hex_color_code()} />
	<Icon.Printer size="40" color={random_hex_color_code()} />
	<Icon.QrCode size="40" color={random_hex_color_code()} />
	<Icon.Quote size="40" color={random_hex_color_code()} />
	<Icon.Radio size="40" color={random_hex_color_code()} />
	<Icon.RadioReceiver size="40" color={random_hex_color_code()} />
	<Icon.Redo size="40" color={random_hex_color_code()} />
	<Icon.RefreshCcw size="40" color={random_hex_color_code()} />
	<Icon.RefreshCw size="40" color={random_hex_color_code()} />
	<Icon.Regex size="40" color={random_hex_color_code()} />
	<Icon.Repeat size="40" color={random_hex_color_code()} />
	<Icon.Repeat1 size="40" color={random_hex_color_code()} />
	<Icon.Reply size="40" color={random_hex_color_code()} />
	<Icon.ReplyAll size="40" color={random_hex_color_code()} />
	<Icon.Rewind size="40" color={random_hex_color_code()} />
	<Icon.Rocket size="40" color={random_hex_color_code()} />
	<Icon.RockingChair size="40" color={random_hex_color_code()} />
	<Icon.RotateCcw size="40" color={random_hex_color_code()} />
	<Icon.RotateCw size="40" color={random_hex_color_code()} />
	<Icon.Rss size="40" color={random_hex_color_code()} />
	<Icon.Ruler size="40" color={random_hex_color_code()} />
	<Icon.RussianRuble size="40" color={random_hex_color_code()} />
	<Icon.Save size="40" color={random_hex_color_code()} />
	<Icon.Scale size="40" color={random_hex_color_code()} />
	<Icon.Scan size="40" color={random_hex_color_code()} />
	<Icon.ScanLine size="40" color={random_hex_color_code()} />
	<Icon.Scissors size="40" color={random_hex_color_code()} />
	<Icon.ScreenShare size="40" color={random_hex_color_code()} />
	<Icon.ScreenShareOff size="40" color={random_hex_color_code()} />
	<Icon.Search size="40" color={random_hex_color_code()} />
	<Icon.Send size="40" color={random_hex_color_code()} />
	<Icon.SeparatorHorizontal size="40" color={random_hex_color_code()} />
	<Icon.SeparatorVertical size="40" color={random_hex_color_code()} />
	<Icon.Server size="40" color={random_hex_color_code()} />
	<Icon.ServerCrash size="40" color={random_hex_color_code()} />
	<Icon.ServerOff size="40" color={random_hex_color_code()} />
	<Icon.Settings size="40" color={random_hex_color_code()} />
	<Icon.Settings2 size="40" color={random_hex_color_code()} />
	<Icon.Share size="40" color={random_hex_color_code()} />
	<Icon.Share2 size="40" color={random_hex_color_code()} />
	<Icon.Sheet size="40" color={random_hex_color_code()} />
	<Icon.Shield size="40" color={random_hex_color_code()} />
	<Icon.ShieldAlert size="40" color={random_hex_color_code()} />
	<Icon.ShieldCheck size="40" color={random_hex_color_code()} />
	<Icon.ShieldClose size="40" color={random_hex_color_code()} />
	<Icon.ShieldOff size="40" color={random_hex_color_code()} />
	<Icon.Shirt size="40" color={random_hex_color_code()} />
	<Icon.ShoppingBag size="40" color={random_hex_color_code()} />
	<Icon.ShoppingCart size="40" color={random_hex_color_code()} />
	<Icon.Shovel size="40" color={random_hex_color_code()} />
	<Icon.Shrink size="40" color={random_hex_color_code()} />
	<Icon.Shuffle size="40" color={random_hex_color_code()} />
	<Icon.Sidebar size="40" color={random_hex_color_code()} />
	<Icon.SidebarClose size="40" color={random_hex_color_code()} />
	<Icon.SidebarOpen size="40" color={random_hex_color_code()} />
	<Icon.Sigma size="40" color={random_hex_color_code()} />
	<Icon.Signal size="40" color={random_hex_color_code()} />
	<Icon.SignalHigh size="40" color={random_hex_color_code()} />
	<Icon.SignalLow size="40" color={random_hex_color_code()} />
	<Icon.SignalMedium size="40" color={random_hex_color_code()} />
	<Icon.SignalZero size="40" color={random_hex_color_code()} />
	<Icon.SkipBack size="40" color={random_hex_color_code()} />
	<Icon.SkipForward size="40" color={random_hex_color_code()} />
	<Icon.Skull size="40" color={random_hex_color_code()} />
	<Icon.Slack size="40" color={random_hex_color_code()} />
	<Icon.Slash size="40" color={random_hex_color_code()} />
	<Icon.Sliders size="40" color={random_hex_color_code()} />
	<Icon.Smartphone size="40" color={random_hex_color_code()} />
	<Icon.SmartphoneCharging size="40" color={random_hex_color_code()} />
	<Icon.Smile size="40" color={random_hex_color_code()} />
	<Icon.Snowflake size="40" color={random_hex_color_code()} />
	<Icon.SortAsc size="40" color={random_hex_color_code()} />
	<Icon.SortDesc size="40" color={random_hex_color_code()} />
	<Icon.Speaker size="40" color={random_hex_color_code()} />
	<Icon.Sprout size="40" color={random_hex_color_code()} />
	<Icon.Square size="40" color={random_hex_color_code()} />
	<Icon.Star size="40" color={random_hex_color_code()} />
	<Icon.StarHalf size="40" color={random_hex_color_code()} />
	<Icon.StopCircle size="40" color={random_hex_color_code()} />
	<Icon.StretchHorizontal size="40" color={random_hex_color_code()} />
	<Icon.StretchVertical size="40" color={random_hex_color_code()} />
	<Icon.Strikethrough size="40" color={random_hex_color_code()} />
	<Icon.Subscript size="40" color={random_hex_color_code()} />
	<Icon.Sun size="40" color={random_hex_color_code()} />
	<Icon.Sunrise size="40" color={random_hex_color_code()} />
	<Icon.Sunset size="40" color={random_hex_color_code()} />
	<Icon.Superscript size="40" color={random_hex_color_code()} />
	<Icon.SwissFranc size="40" color={random_hex_color_code()} />
	<Icon.SwitchCamera size="40" color={random_hex_color_code()} />
	<Icon.Table size="40" color={random_hex_color_code()} />
	<Icon.Tablet size="40" color={random_hex_color_code()} />
	<Icon.Tag size="40" color={random_hex_color_code()} />
	<Icon.Target size="40" color={random_hex_color_code()} />
	<Icon.Tent size="40" color={random_hex_color_code()} />
	<Icon.Terminal size="40" color={random_hex_color_code()} />
	<Icon.TerminalSquare size="40" color={random_hex_color_code()} />
	<Icon.TextCursor size="40" color={random_hex_color_code()} />
	<Icon.TextCursorInput size="40" color={random_hex_color_code()} />
	<Icon.Thermometer size="40" color={random_hex_color_code()} />
	<Icon.ThermometerSnowflake size="40" color={random_hex_color_code()} />
	<Icon.ThermometerSun size="40" color={random_hex_color_code()} />
	<Icon.ThumbsDown size="40" color={random_hex_color_code()} />
	<Icon.ThumbsUp size="40" color={random_hex_color_code()} />
	<Icon.Ticket size="40" color={random_hex_color_code()} />
	<Icon.Timer size="40" color={random_hex_color_code()} />
	<Icon.TimerOff size="40" color={random_hex_color_code()} />
	<Icon.TimerReset size="40" color={random_hex_color_code()} />
	<Icon.ToggleLeft size="40" color={random_hex_color_code()} />
	<Icon.ToggleRight size="40" color={random_hex_color_code()} />
	<Icon.Tornado size="40" color={random_hex_color_code()} />
	<Icon.Trash size="40" color={random_hex_color_code()} />
	<Icon.Trash2 size="40" color={random_hex_color_code()} />
	<Icon.Trello size="40" color={random_hex_color_code()} />
	<Icon.TrendingDown size="40" color={random_hex_color_code()} />
	<Icon.TrendingUp size="40" color={random_hex_color_code()} />
	<Icon.Triangle size="40" color={random_hex_color_code()} />
	<Icon.Truck size="40" color={random_hex_color_code()} />
	<Icon.Tv size="40" color={random_hex_color_code()} />
	<Icon.Tv2 size="40" color={random_hex_color_code()} />
	<Icon.Twitch size="40" color={random_hex_color_code()} />
	<Icon.Twitter size="40" color={random_hex_color_code()} />
	<Icon.Type size="40" color={random_hex_color_code()} />
	<Icon.Umbrella size="40" color={random_hex_color_code()} />
	<Icon.Underline size="40" color={random_hex_color_code()} />
	<Icon.Undo size="40" color={random_hex_color_code()} />
	<Icon.Unlink size="40" color={random_hex_color_code()} />
	<Icon.Unlink2 size="40" color={random_hex_color_code()} />
	<Icon.Unlock size="40" color={random_hex_color_code()} />
	<Icon.Upload size="40" color={random_hex_color_code()} />
	<Icon.UploadCloud size="40" color={random_hex_color_code()} />
	<Icon.User size="40" color={random_hex_color_code()} />
	<Icon.UserCheck size="40" color={random_hex_color_code()} />
	<Icon.UserMinus size="40" color={random_hex_color_code()} />
	<Icon.UserPlus size="40" color={random_hex_color_code()} />
	<Icon.UserX size="40" color={random_hex_color_code()} />
	<Icon.Users size="40" color={random_hex_color_code()} />
	<Icon.Verified size="40" color={random_hex_color_code()} />
	<Icon.Vibrate size="40" color={random_hex_color_code()} />
	<Icon.Video size="40" color={random_hex_color_code()} />
	<Icon.VideoOff size="40" color={random_hex_color_code()} />
	<Icon.View size="40" color={random_hex_color_code()} />
	<Icon.Voicemail size="40" color={random_hex_color_code()} />
	<Icon.Volume size="40" color={random_hex_color_code()} />
	<Icon.Volume1 size="40" color={random_hex_color_code()} />
	<Icon.Volume2 size="40" color={random_hex_color_code()} />
	<Icon.VolumeX size="40" color={random_hex_color_code()} />
	<Icon.Wallet size="40" color={random_hex_color_code()} />
	<Icon.Wand size="40" color={random_hex_color_code()} />
	<Icon.Watch size="40" color={random_hex_color_code()} />
	<Icon.Waves size="40" color={random_hex_color_code()} />
	<Icon.Webcam size="40" color={random_hex_color_code()} />
	<Icon.Wifi size="40" color={random_hex_color_code()} />
	<Icon.WifiOff size="40" color={random_hex_color_code()} />
	<Icon.Wind size="40" color={random_hex_color_code()} />
	<Icon.WrapText size="40" color={random_hex_color_code()} />
	<Icon.Wrench size="40" color={random_hex_color_code()} />
	<Icon.X size="40" color={random_hex_color_code()} />
	<Icon.XCircle size="40" color={random_hex_color_code()} />
	<Icon.XOctagon size="40" color={random_hex_color_code()} />
	<Icon.XSquare size="40" color={random_hex_color_code()} />
	<Icon.Youtube size="40" color={random_hex_color_code()} />
	<Icon.Zap size="40" color={random_hex_color_code()} />
	<Icon.ZapOff size="40" color={random_hex_color_code()} />
	<Icon.ZoomIn size="40" color={random_hex_color_code()} />
	<Icon.ZoomOut size="40" color={random_hex_color_code()} />
</div>
